### ISSUE TITLE
New CK1 (Act 4) achievements

### ISSUE THREAD

**Issue by Condy-jpg** [College-Kings/College-Kings#180]
Two new achievements should be added to steam interface: saving_ryans_privates and ready_player_three

They are part of v14 scenes 1-10.

**Comment by KiloOscarSix** [comment]
Achievements add to API. Need Icons College-Kings/College-Kings-2#230

**Comment by Condy-jpg** [comment]
https://drive.google.com/drive/folders/15bDc3wo3DMl9ot5pvNZZyxdJxC6fvg9g @KiloOscarSix (two most recent ones)

**Comment by KiloOscarSix** [comment]
![image](https://user-images.githubusercontent.com/26691547/163057744-0dc829aa-1b9e-45f3-83ca-0ee790769f27.png)
?

**Comment by Condy-jpg** [comment]
saving_ryans_privates and ready_player_three

**Comment by Condy-jpg** [comment]
![image](https://user-images.githubusercontent.com/84246708/163057954-5bc94ffb-31a3-4bc3-bd4f-47dcf4dd5d51.png)

**Comment by KiloOscarSix** [comment]
oops had the sort the wrong way

**Comment by KiloOscarSix** [comment]
![image](https://user-images.githubusercontent.com/26691547/163058508-668262d1-0120-4922-a822-5d903089fb5e.png)
