### ISSUE TITLE
CK1 voice acting

### ISSUE THREAD

**Issue by Condy-jpg** [College-Kings/College-Kings#182]
```
            if voice_acted:
                $ renpy.sound.play("music/v14/va/Scene 1 - dbj_slow_2loops.mp3", loop=True)
```

But files aren't there

**Comment by KiloOscarSix** [comment]
[va.zip](https://github.com/College-Kings/College-Kings/files/8476736/va.zip)
@Condy-jpg

**Comment by Condy-jpg** [comment]
Think I got it in the end
9562232918a4785578f354c66567daa48759d7e1

**Comment by KiloOscarSix** [comment]
ahaha i was watching git feed thinking wtf is going on xD

**Comment by Condy-jpg** [comment]
Doing it online, don't have the repository on this machine
