### ISSUE TITLE
AttributeError: 'MainCharacter' object has no attribute 'relationships'

### ISSUE THREAD

**Issue by Condy-jpg** [College-Kings/College-Kings#193]
![image](https://user-images.githubusercontent.com/84246708/163457333-ec1ebd7d-a9be-4e09-b2c7-1cbe718a3b01.png)

Ticket 0801: https://discord.com/channels/745662812335898806/964235278703267850

**Comment by KiloOscarSix** [comment]
MainCharacter is an old class. Will need example save to fix
