### ISSUE TITLE
Steam report - advanced options turning to black screen

### ISSUE THREAD

**Issue by Condy-jpg** [College-Kings/College-Kings#200]
The advance page on path builder seems to be glitched for me. I can select addition details of my choices from CK1 but theirs no confirm button so I click return and the screen goes black. Step 5 is blank nothing to select, I tried the advance button at each step lets me click the boxes but always goes black screen after hitting return button and have to close the game.

**Comment by Condy-jpg** [comment]
Heard that pressing ESC helps

**Comment by KiloOscarSix** [comment]
duplicate of #197
