### ISSUE TITLE
There is an issue in the Murder mystery scene, where I cannot access certain parts of the boat and find the rest of the players.

### ISSUE THREAD

**Issue by kedwards72** [College-Kings/College-Kings#208]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. 
2. 
3. 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 7.6.4]

**Additional context**

**Comment by Condy-jpg** [comment]
Well, which areas and which players so we can look into it?

**Comment by kedwards72** [comment]
I can't get to front gallery, utility, balcony, or rear. Also there are only 3 levels to the boat correct?

**Comment by Condy-jpg** [comment]
There's three levels, and you can reach the utility, front gallery and the balcony by going forward (up) from the right gallery.
![image](https://user-images.githubusercontent.com/84246708/163827028-6aa7f932-2a56-4adb-8037-a6f75cc232ca.png)

**Comment by kedwards72** [comment]
There is no highlight for me to access it there. I "murdered" ryan and emre, but I still can't get to that area.

**Comment by Condy-jpg** [comment]
![image](https://user-images.githubusercontent.com/84246708/163827611-93240c46-3f10-42a0-8a66-0a3f4ffd4b5d.png)
Clicking here does nothing?

**Comment by kedwards72** [comment]
Clicking at the top worked thank you! Is there a way to get to the rear or no?

**Comment by Condy-jpg** [comment]
Yes, again click to go "up" from either the Right or Left walkways.

![image](https://user-images.githubusercontent.com/84246708/163828225-35633f2c-2a94-4a57-adad-136233b8f8bd.png)
