### ISSUE TITLE
website cleanup errors

### ISSUE THREAD

**Issue by rtrunkhill** [College-Kings/College-Kings#209]
![image](https://user-images.githubusercontent.com/28711410/164145331-edd9fd09-aa9f-4abd-ba8d-276934c1e58e.png)
Assuming the entire CK1 is free on the site as well as steam, not just act 1

typo:
![image](https://user-images.githubusercontent.com/28711410/164145375-fed33dcb-7f70-4a2b-a0b2-0d83c7e01443.png)

**Comment by KiloOscarSix** [comment]
> @KiloOscarSix is this still valid? If so, I can take a look at it later today.

No, the website is no longer developed here. Instead it's now a Wordpress app
