### ISSUE TITLE
ck1 saves

### ISSUE THREAD

**Issue by Frosty788** [College-Kings/College-Kings#210]
**Describe the bug**
none of my ck1 saves are working for ck2
**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. 
2. 
3. 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 7.6.4]

**Additional context**

**Comment by KiloOscarSix** [comment]
@Frosty788 We're going to need more details to address this. Do you have an error report and can you upload your save file here.

**Comment by KiloOscarSix** [comment]
Over a month old with no response.
Please reopen this ticket if response changes.
