### ISSUE TITLE
Relationship Status Changing from CK1 to CK2

### ISSUE THREAD

**Issue by Izik44** [College-Kings/College-Kings#216]
I notice that some of the relationships status change from the vey ending of CK1 to the beginning of CK2. example ; Penelope has a relationship status of "Likes" at the end of CK1 but when I transfer that save to CK2 it changes to "Friend". Which eliminates certain options with Penelope early in CK2 such as going on a date wither instead of the lagoon with Jenny.

**Comment by Izik44** [comment]
any update ???

**Comment by KiloOscarSix** [comment]
Hi, @Izik44 I'm away for 2 days. Once I'm back I'll push fixes to amend the relationship issues

**Comment by Izik44** [comment]
has there been a fix to this yet ?

**Comment by KiloOscarSix** [comment]
Yes, should be fixed in the latest update, if you're playing from launcher update should be pushed soon
