### ISSUE TITLE
CK1 Save not loading

### ISSUE THREAD

**Issue by JEPelerin** [College-Kings/College-Kings#217]
Trying to load save from last screen of game (ie screen advertising CK2). Get phone over black screen with text <Image 'v14s09_8a' not found> in upper right corner.

Clicking "Exit Phone" takes me back to the ck2 load screen. 

Have same problem with saves from airport scene (eg just after last decision (what did Penelope like best); and final image of Ms Rose).

**Comment by KiloOscarSix** [comment]
Please upload your save here so we can replicate this error

**Comment by KiloOscarSix** [comment]
Over a month old with no response, closing ticket.
Please reopen this ticket if response changes.
