### ISSUE TITLE
CK2 relationship status

### ISSUE THREAD

**Issue by Izik44** [College-Kings/College-Kings#219]
Ok so im still noticing that relationship status are being changed from Ck1 over to CK2. Penelope ends CK1 with a "likes" status but in CK2 when i upload that CK1 save, it changes to "friends". Was this issue going to get resolved ?

**Comment by KiloOscarSix** [comment]
What version are you playing, and can you upload your save here so we can replicate the issue

**Comment by Izik44** [comment]
the latest version .16s 
 
[16-4-LT1.zip](https://github.com/College-Kings/College-Kings/files/8694583/16-4-LT1.zip)

**Comment by Izik44** [comment]
any news

**Comment by KiloOscarSix** [comment]
We are continually attempting to port all existing data to CK2, your saves along with those provided by the few having relationship issues are instrumental in helping us complete the compatibility layer.
I would recommend using PB or Recap if this save isn't working on the latest update as the next push to Launcher/Steam will likely be next week
