### ISSUE TITLE
Incorrect save transfer

### ISSUE THREAD

**Issue by LucarioDaBosse** [College-Kings/College-Kings#223]
**Describe the bug**
Transferred CK1 save file, where Lauren was my girlfriend and I had some friends with benefits, but everyone is shown as just a friend in the relationships

**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. All i did was load the old file
2. 
3. 

**Expected behaviour**
The save stuff to be all correct

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Version: 11, os build: 22000.739

**Additional context**

**Comment by KiloOscarSix** [comment]
"save stuff to be all correct" isn't helpful.

What exactly is wrong with the save?
Also please provide a save file so we can verify it's fixed
