### ISSUE TITLE
Text conversation with Emmy

### ISSUE THREAD

**Issue by rtrunkhill** [College-Kings/College-Kings#236]
![image](https://user-images.githubusercontent.com/28711410/180874108-4f157db3-36af-4b54-b78e-79c92b14be4b.png)

it's only showing one side of the conversation in the Simplr app, this is in paris just before leaving for amsterdam

**Comment by KiloOscarSix** [comment]
Fixed in 5c34b70560c5556a06824a95e0871f43691e4cc8
