### ISSUE TITLE
Problem with importing save file from CK1 to CK2

### ISSUE THREAD

**Issue by mpogalex** [College-Kings/College-Kings#246]
**Describe the bug**
After importing save file from CK1 and starting CK2 I've got duplicated Kiwii posts without my likes and comments, I mean - i still have my old post with my likes and comments from CK1 but also got empty duplicated posts.

**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. Link to save file from CK1
https://drive.google.com/file/d/10LUcPiu-h0MBYh384X79aBnuUk_F6B0t/view?usp=sharing
2. Link to the video - i made video - where you can see the duplicates 
https://drive.google.com/file/d/1FwxTU5BY8Wk9Om7z7nooWEen3BAo6dFJ/view?usp=sharing
 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 7.6.4]

**Additional context**
Maybe there is another method to import saves from CK1 to CK2 without bugs? I used just option on the top of the screen while starting new game in College Kings 2 and also I tried to load option in Load menu as well.

**Comment by KiloOscarSix** [comment]
Fixed in v1.2.0

**Comment by KiloOscarSix** [comment]
> **Describe the bug** Sorry for bothering you again After importing save file from CK1 and starting CK2 I've got duplicated Kiwii posts without my likes and comments, I mean - i still have my old post with my likes and comments from CK1 but also got empty duplicated posts. In my previous ticket you answered that this problem is fixed in 1.2.0 version. The question is - how to get this 1.2.0 version? I bought game on steam, and there is only 1.1.7s version. How can I get this 1.2.0 version in steam? I checked in steam configures and it seems that there is no newer updates that 1.1.7s.
> 
> **To Reproduce** Here is link with video in which you can see the bug and the version of the game [drive.google.com/file/d/1SAynnGcsEYZjOfm0bM-iPNS-d8IQXH_X/view?usp=sharing](https://drive.google.com/file/d/1SAynnGcsEYZjOfm0bM-iPNS-d8IQXH_X/view?usp=sharing)
> 
> **Expected behaviour** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows]
> * Version [e.g. 7.6.4]
> 
> **Additional context** Add any other context about the problem here.

**Comment by KiloOscarSix** [comment]
@mpogalex v1.2.0 isn't publicly available yet.

Once all the issues reported have been fixed or addressed then we'll release the update
