### ISSUE TITLE
Another problem with the relationships...

### ISSUE THREAD

**Issue by nfAdrian** [College-Kings/College-Kings#249]
After I click on the relationships app, when I try to click on the 'exit phone' text, it doesn't let me. I have to press the home button (or the phone screen in the top right), in order to exit the phone.

https://vimeo.com/743972808

**Comment by nafck** [comment]
A weird thing to notice: this problem doesn't occur in CK2. There, I can exit the phone even from the relationships app

**Comment by KiloOscarSix** [comment]
I'm unable to replicate this issue nor do I see a reason why it should happen.

Are you loading a save or starting a fresh game?

**Comment by nafck** [comment]
Now I'm starting a fresh game

**Comment by nafck** [comment]
> After I click on the relationships app, when I try to click on the 'exit phone' text, it doesn't let me. I have to press the home button (or the phone screen in the top right), in order to exit the phone.
> 
> https://vimeo.com/743972808



!!!

Wait, I've noticed something: this problem triggers only during the free roams

**Comment by nafck** [comment]
> > After I click on the relationships app, when I try to click on the 'exit phone' text, it doesn't let me. I have to press the home button (or the phone screen in the top right), in order to exit the phone.
> > https://vimeo.com/743972808
> 
> !!!
> 
> Wait, I've noticed something: this problem triggers only during the free roams

And this exact issue happens in CK2 aswell!

**Comment by KiloOscarSix** [comment]
> Wait, I've noticed something: this problem triggers only during the free roams

Nice! This is big information as the phone is handled differently in story/free roam. I'll hunt down the issue later today, thanks 👍

**Comment by KiloOscarSix** [comment]
> And this exact issue happens in CK2 aswell!

Aye with the submodules the phone should behave exactly the same between ck1 and ck2 as they both pull from the same phone-repo

**Comment by nafck** [comment]
> > And this exact issue happens in CK2 aswell!
> 
> Aye with the submodules the phone should behave exactly the same between ck1 and ck2 as they both pull from the same phone-repo

Should I move this issue to CK2's repo?

**Comment by nfAdrian** [comment]
Copied here and (later) fixed:

https://github.com/College-Kings/College-Kings-2/issues/1009
