### ISSUE TITLE
Note about a status

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#252]
https://postimg.cc/WqpzDYV2

You can see that I have Penelope and Nora with the 'friends' status and not 'friend', but this is in fact the 'likes' status. So I think there should be some changes here, because players would misunderstand this and they would believe that their relationships were reset to 'friend'. While this is a screenshot from CK1, the status stays the same in CK2, with the save transfer.

To explain it better: I have Penelope and Nora on the 'likes' status, but on the relationships app, it's displayed as 'friends' (which is different from 'friend')

**Comment by Condy-jpg** [comment]
In other words CK2 is fine, we just need to take out the final S.

**Comment by nafck** [comment]
Yeah. However, 'likes' shouldn't be confused with 'friend'. I mean, in the relationships, it should have a more representative name

**Comment by Condy-jpg** [comment]
I think we're wanting to reduce the number of layers in relationships.

**Comment by nafck** [comment]
Probably

**Comment by nafck** [comment]
A bit off-topic (and more of a suggestion):

https://postimg.cc/gwV6nB57

When players reach this phase in CK1, maybe at least a message saying 'Save your game here' can be shown on the screen.

**Comment by KiloOscarSix** [comment]
Fixed in ep4 character/relationship rework
