### ISSUE TITLE
'Default' scenes

### ISSUE THREAD

**Issue by nafck** [College-Kings/College-Kings#262]
https://postimg.cc/y3dbyz6t

There's something similar with that Naomi scene from CK2. This time, it's about 'dreaming of Riley' and 'first time with Aubrey' which are available in the gallery scene (accessible now without any error) without even getting them in any of my playthroughs.

**Comment by Condy-jpg** [comment]
[757c2c3](https://github.com/College-Kings/College-Kings/commit/757c2c3638f3de60a6f12528a340469be2219ffc)
