### ISSUE TITLE
'Dreaming of Riley'...

### ISSUE THREAD

**Issue by nafck** [College-Kings/College-Kings#265]
I still get that 'dreaming of Riley' scene in the gallery (without going through it), unless it's there by default.

_Originally posted by @nafck in https://github.com/College-Kings/College-Kings/issues/262#issuecomment-1280806788_

**Comment by Condy-jpg** [comment]
It's not there by default, you need to reach a specific label, and that label is unavoidable (you don't need to reach the end of the scene or go through all dialogue options to unlock it)
