### ISSUE TITLE
Fight menu not in english

### ISSUE THREAD

**Issue by nafck** [College-Kings/College-Kings#266]
![1](https://user-images.githubusercontent.com/108369429/197333302-ba54ce9e-2c2f-4078-8142-e9c6429f664d.png)

And no, I'm not playing with french subtitles (or chinese or something else).

**Comment by nafck** [comment]
Why it worked only by deleting the translations folder and re-initializing it? ...

**Comment by KiloOscarSix** [comment]
because i've updated it ;)
