### ISSUE TITLE
game crash when loading CK1's saving files.

### ISSUE THREAD

**Issue by kennyboy800515** [College-Kings/College-Kings#269]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. 
2. 
3. 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 7.6.4]

**Additional context**

**Comment by KiloOscarSix** [comment]
Stale and no valid information
