### ISSUE TITLE
game crash when loadilng CK1's file

### ISSUE THREAD

**Issue by kennyboy800515** [College-Kings/College-Kings#270]
**Describe the bug**
game crash when loading CK1's saving files.

**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. open CK2
2. choose load CK1's saving file
3. game crash

**Expected behaviour**
please clear the bug and let me download all my CK1 progress in CK2

**Screenshots**
![image](https://user-images.githubusercontent.com/116493445/197389822-2e9c3fef-8b32-4be3-b279-e4291fecf42b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v.1.1.7s

**Additional context**

**Comment by KiloOscarSix** [comment]
Cannot replicate on latest 3.1.0 should fix a lot of these bugs
