### ISSUE TITLE
Old save file cant be used anymore

### ISSUE THREAD

**Issue by PotgrondSlurper** [College-Kings/College-Kings#271]
**Describe the bug**
I saved at the end of part 1 at the screen which said come back when episode 2 is out
but now it jumped to the screen which says: "wait for episode 3 to be released"
**To Reproduce**
Steps to reproduce the behaviour or save the file:
1. 
2. 
3. 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 7.6.4]

**Additional context**

**Comment by KiloOscarSix** [comment]
Please send some save files for us to investigate

**Comment by KiloOscarSix** [comment]
Please roll back a few scenes, remake the save and load that save on ck2, should fix the issue
