### ISSUE TITLE
CK1 Save won't load

### ISSUE THREAD

**Issue by Wilm3R00** [College-Kings/College-Kings#273]
**Describe the bug**
A clear and concise description of what the bug is. My save from CK1 won't load says some value won't load or something.

**To Reproduce**
Steps to reproduce the behaviour or save the file:
TypeError: __new__() missing 1 required positional argument: 'value'
That is what it says is the problem.

**Expected behaviour**
A clear and concise description of what you expected to happen. I expected it to load the save file and let me play.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 11
 - Version [e.g. 7.6.4] 22H2

**Additional context**

**Comment by KiloOscarSix** [comment]
This, unfortunately, isn't fixable, we suspect this error occurred to some players during an update to the underlying game engine. Please use Path Builder or the Recap mechanic to rebuild your save.
