### ISSUE TITLE
v12, scene 7: Aubrey doesn't see Josh

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

v12, scene 7

### Priority

High

### Bug Description

If Josh goes to Europe, in the 2nd talk with MC from the ferry game, they could both be seen by Aubrey, if she's still in her initial place. However, that eye which indicates that a person can be seen is closed the entire time:

![joshaubs](https://user-images.githubusercontent.com/108369429/216758321-7736fa8d-1098-4879-a749-95cf2bf5ed83.png)

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
@nfaStefan do you know if Josh can be "killed" in any other instance?

**Comment by nfaStefan** [comment]
I've tried it, and no. That's the only the place where he can be *murdered* without being spotted.

**Comment by KiloOscarSix** [comment]
Ok then this is an Art issue as Aubrey needs to be looking away

**Comment by Chinay-Domitrix** [comment]
It is actually possible for him to shift from seen to unseen because Aubrey, given that the player chooses the right choices, does actually move, after which he would become unseen. On the flip side, Josh never switches places.

**Comment by nfaStefan** [comment]
I know about that situation, but what if the players plans to take out Josh before Aubrey?

**Comment by Chinay-Domitrix** [comment]
Then it goes to the default caught screen, ig

**Comment by nfaStefan** [comment]
Well, at the current state, it doesn't.

> Then it goes to the default caught screen, ig

**Comment by Chinay-Domitrix** [comment]
Yeah I’m aware; what I’m saying is that instead of redoing the art, we should keep track of Aubrey’s location and change Josh’s visibility state accordingly

**Comment by nfaStefan** [comment]
Let's see what the higher ranks think about it.

**Comment by KiloOscarSix** [comment]
@Chinay-Domitrix @nfaStefan Could someone check if this is fixed with the latest changes

**Comment by nfaStefan** [comment]
![josh](https://user-images.githubusercontent.com/108369429/235224444-8f65f221-099e-4d86-9643-ea5c054d4552.png)

It seems to work, but I can't test with the *caught in the act* part, due to another issue (which I'm going to make like right now).
