### ISSUE TITLE
v6, Wolves party free roam: All the relics are the same

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

v6

### Priority

Low

### Bug Description

I see there's a variable which is used for all the relics that can be clicked in the Wolves' office. I don't know if this is intentional, but if I click on the exact same relic 4 times, it takes me to that fr3relics label. Maybe a different variable for each variable could be used?

![relics](https://user-images.githubusercontent.com/108369429/216758538-5d68725a-5fbb-45d8-bb5e-7ed544053166.png)

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
Fixed
