### ISSUE TITLE
v7: Game asking to enter the player name, when it was already set from the beginning

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

v7, but I don't think that's the only one

### Priority

High

### Bug Description

This happened while I was playtesting CK1... But I have a feeling that it's not the only scene where this could have happened:

https://www.youtube.com/watch?v=4Ggvsxnblp0&ab_channel=FlaviusNecoara

### Additional context

I get the feeling this might happen in CK2 (and no, I haven't chosen the pathbuilder as a start, I went for a *new game*)

### What is the OS version you are playing on?

Windows

**Comment by nfaStefan** [comment]
Ok, I don't know what exactly happened, but it seems that it was fixed, somehow (or at least, I didn't encounter it anymore).

**Comment by nfaStefan** [comment]
... It looks like I need to reopen this, because if the game data was previously removed (or someone plays CK1 for the very first time) this super weird behaviour reappears.

**Comment by KiloOscarSix** [comment]
unable to replicate
