### ISSUE TITLE
Achievements not earnable when starting a new game

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

I don't know the script for the achievements

### Priority

High

### Bug Description

I was continuing my *faulty* playtest from #281, and by mistake I've noticed that the earned achievements were removed:

![achiev1](https://user-images.githubusercontent.com/108369429/221488175-01559877-01a4-45b7-b736-58388bd9f478.png)
![achiev2](https://user-images.githubusercontent.com/108369429/221488178-cf1c7d5c-ccf2-4867-a587-dee5484d0178.png)

And I didn't get the pop-up either for the earned ones. Remember that I started a new game from the very beginning.

### What is the OS version you are playing on?

Windows

**Comment by nfaStefan** [comment]
I guess deleting everything and starting all over kinda fixed this. 💀

**Comment by nfaStefan** [comment]
Gonna reopen it, due to the return of #281.

**Comment by KiloOscarSix** [comment]
I suspect "path_builder" variable was somehow enabled should be fixed in latest PB update
