### ISSUE TITLE
ep4_s69b - Error when load CK 1 saves

### ISSUE THREAD

**Issue by kabanel1o** [College-Kings/College-Kings#283]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Scene number

ep4_s69b

### Priority

Urgent

### Bug Description

When I transfer saves from CK1 to the CK2 image 'v14s10_5' not found appears in the upper left corner of the screen, 
a fraternity selection window appears in the center, because my frat data has been corrupted after selection throws to the end screen. CK 1 v1.2.16s, CK 2 v2.2.12s

### Additional context

![image](https://user-images.githubusercontent.com/126707973/222223554-97ca69cc-2efd-4d89-9d05-a62036e7ccac.png)
![image](https://user-images.githubusercontent.com/126707973/222224573-14894c3a-18d4-461a-88bb-8d33771319de.png)

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
New CK1 saves now load correctly into ck2 replaced the end_game screen with a image to improve saving
