### ISSUE TITLE
Non empty block -> no game start

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

No idea

### Priority

Urgent

### Bug Description

I'm getting this issue when trying to start CK1 now:

```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/tl/espanol/v1/v1.rpy", line 196: translate statement expects a non-empty block.
    translate espanol starta_159d4a13:
                                      ^

Ren'Py Version: Ren'Py 8.0.3.22090809
Sat Mar  4 00:52:20 2023
```

I gotta ask though... Do I have to delete that translations folder again? ...

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
delete tl/ folder
