### ISSUE TITLE
ep7_s756  - Exception thrown after pledging to the apes

### ISSUE THREAD

**Issue by aestheatae** [College-Kings/College-Kings#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

ep7_s756 

### Priority

Urgent

### Bug Description

Bug description:
Right after pledging to the apes, the exception appears and cannot continue (pledging to the wolves works o.k.).

Looking at the code at line 4690 in "game/v7/v7.rpy", there is a remnant of
$ reputation.add_point(Reputations.TROUBLEMAKER, 3) 

The same remnant is yet to be found also on line 4412 in the same file:
$ reputation.add_point(Reputations.TROUBLEMAKER, 2)

Exception traceback:
--------------------------------------------------------------------------

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/v7/v7.rpy", line 4690, in <module>
  File "game/reputation.rpy", line 69, in add_point
KeyError: <Reputations.TROUBLEMAKER: 'troublemaker'>

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "v7/v7.rpyc", line 4690, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\College Kings\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\College Kings\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/v7/v7.rpy", line 4690, in <module>
  File "game/reputation.rpy", line 69, in add_point
KeyError: <Reputations.TROUBLEMAKER: 'troublemaker'>

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
College Kings 1.2.10s (SHA: 96d9ed0ef)
Tue Apr  4 16:52:17 2023
[/code]

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
Fixed in latest
