### ISSUE TITLE
Enlightened phone with no notifications

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

I guess the phone script

### Priority

Normal

### Bug Description

Ok, why does the phone glow up when I have no new messages (or no new Kiwii posts)?

https://www.youtube.com/watch?v=hhLYBqGgHIQ&feature=youtu.be&ab_channel=FlaviusNecoara

### What is the OS version you are playing on?

Windows

**Comment by nfaStefan** [comment]
Not I had to see this... It went back to *normal* after receiving a new text:

https://www.youtube.com/watch?v=709J3aepKaA&ab_channel=FlaviusNecoara

**Comment by KiloOscarSix** [comment]
because im mean

**Comment by nfaStefan** [comment]
Ok, I didn't know I was talking to condy. 💀
