### ISSUE TITLE
Double application 💀 

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

Starting the game

### Priority

High

### Bug Description

I know the solution would be to delete (again) all the rpyc files, but... Better make a ticket, just in case:

I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name ('game/phone/Application_ren.py', 1682276495, 1077) is defined twice, at game/phone/Application_ren.py:2 and game/phone/Application_ren.py:2.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "D:\renpy\renpy\main.py", line 492, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "D:\renpy\renpy\script.py", line 310, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "D:\renpy\renpy\script.py", line 888, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "D:\renpy\renpy\script.py", line 525, in finish_load
    check_name(node)
  File "D:\renpy\renpy\script.py", line 501, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('game/phone/Application_ren.py', 1682276495, 1077) is defined twice, at game/phone/Application_ren.py:2 and game/phone/Application_ren.py:2.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23042213
College Kings 
Sun Apr 23 22:02:16 2023

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
yep delete rpyc
