### ISSUE TITLE
Breaking syntax

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

In the variables file, maybe?

### Priority

High

### Bug Description

Amazing, just updated the repo, and now I get this:

```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/variables.rpy", line 270: invalid syntax
    julia = NonPlayableCharacter("Julia")
           ^

Ren'Py Version: Ren'Py 8.1.0.23042213
Tue Apr 25 02:32:12 2023
```

And I can't start the game now, by the way. 💀 

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
fixed
