### ISSUE TITLE
Server connections are timing out for Lovense support.

### ISSUE THREAD

**Issue by Naberiusx** [College-Kings/College-Kings#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

CK2 ALL

### Priority

High

### Bug Description

Servers are timing out for lovense support causing an infinite not responding loop and crashes. Does NOT leave a trace back file or any oddities in log.txt as it's a loop. Changing the servers to another url renders the lovense connect page free of the loop.

### Expected behavior

No game breaking or infinite not responding loops when connecting or even trying to load the connect lovense section.

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
Lovense button has been disabled in the latest version while we figure out why the server is timing out

**Comment by KiloOscarSix** [comment]
Fixed in latest
