### ISSUE TITLE
Indentation break

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

V2, looks like

### Priority

High

### Bug Description

Can't start the game because of it:

```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/v2/v2.rpy", line 194: Indentation mismatch.

Ren'Py Version: Ren'Py 8.1.0.23042213
Thu Apr 27 18:27:51 2023
```

### What is the OS version you are playing on?

Windows

**Comment by Chinay-Domitrix** [comment]
#331 should fix all of this
