### ISSUE TITLE
Penelope Path Builder Relationship

### ISSUE THREAD

**Issue by Chinay-Domitrix** [College-Kings/College-Kings#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

Pathbuilder

### Priority

Low

### Bug Description

Is Penelope supposed to have a girlfriend relationship option in path builder?

### Additional context

![image](https://user-images.githubusercontent.com/55807470/235202738-15df44d6-dc08-412f-a00a-1135b317d29d.png)

### What is the OS version you are playing on?

Windows

**Comment by nfaStefan** [comment]
In CK1, no, but the pathbuilder is going to be completely reworked aswell, from what I heard. Besides, Nora and Aubrey GF (and many other relationships) aren't supposed to be in CK1, either.

**Comment by Chinay-Domitrix** [comment]
Resolved #356
