### ISSUE TITLE
KCT Distinction on Path-Built vs Non-Path-Built Games in Release Version

### ISSUE THREAD

**Issue by Chinay-Domitrix** [College-Kings/College-Kings#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

Full game

### Priority

High

### Bug Description

After recently having played a path-built game, I started a fresh game without path-building, and my KCT distribution is 10B/20BF/20TM instead of the usual 1/2/2

### Expected behavior

If I am not mistaken, as stated above, the distribution is supposed to be 1/2/2

### Additional context

![image](https://user-images.githubusercontent.com/55807470/235326803-11c381a4-def2-40bb-997c-9c25e4a74446.png)
(The black bars are because my laptop has a 16:10 aspect ratio)

### What is the OS version you are playing on?

Windows

**Comment by Chloe-Chaser** [comment]
No 20/20/10 is normal

**Comment by KiloOscarSix** [comment]
Can we be mindful of the priority chosen, this doesn't break the game or cause any major impacts to the player so should be tagged as Low or Normal, not high, thanks

**Comment by Chinay-Domitrix** [comment]
I was originally going to tag it normal, but tagged it high because it's the release version
