### ISSUE TITLE
Save file going back a few scenes

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

High

### Bug Description

Why does the *checkpoint* of the save file goes back a few lines in the scene? The save is at the last dialogue in the game, and after loading it, the game goes to *choosing the other's favorites*:

https://www.youtube.com/watch?v=m-yth6bLOW4&feature=youtu.be&ab_channel=FlaviusNecoara

### Additional context

Rolling back on the other save files triggers the same problem.

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
> Rolling back on the other save files triggers the same problem.

Rolling back on saves is never a good idea, you will undo all the save fixes done during loading

**Comment by KiloOscarSix** [comment]
If a save loses its checkpoint instead of throwing an error we now just load the previous checkpoint or the last visited label

**Comment by KiloOscarSix** [comment]
we've made a ton of changes xD
