### ISSUE TITLE
No notification for new messages (without replying)

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

v10, scene 41a and v12, scene 3

### Priority

Normal

### Bug Description

In that 2nd scene, if I choose to reply, the notification does show up after:

https://www.youtube.com/watch?v=9IokorfY1r0&ab_channel=FlaviusNecoara

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
This is intended behaviour to prevent unwanted phone glow, notifications are dependent on replies
