### ISSUE TITLE
V12, scene 7: chopped sign

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

Normal

### Bug Description

Look at the sign, after *freeing* Penelope from the game:

https://www.youtube.com/watch?v=6_zxNswZTeg&ab_channel=FlaviusNecoara

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
fixed in https://github.com/College-Kings/College-Kings/commit/a30c933e6f39254e16a11715e9b64f6dc9b8b037
