### ISSUE TITLE
Checking Kiwii functionalities on older files

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

High

### Bug Description

Well, see for yourself:

https://www.youtube.com/watch?v=tsRr51qoAfo&ab_channel=FlaviusNecoara

Important note: after I first clicked on that heart, near the profile picture, the usernames were removed. And the weirder thing is, after exiting and re-trying the game, the names were still gone.

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
Is this on a save? I'm unable to replicate the missing usernames on a fresh start of ck2

**Comment by nfaStefan** [comment]
Yeah, this was after loading an old save file, before all the rework.

Try this one. And by the way, this was tested only in CK1

[1-1-LT1.zip](https://github.com/College-Kings/College-Kings/files/11413130/1-1-LT1.zip)
