### ISSUE TITLE
v12, scene 7: Nora's ghost leg

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

Normal

### Bug Description

It's a similar issue with that sign from Penelope's cleaning:

https://www.youtube.com/watch?v=7GQQob834Pw&ab_channel=FlaviusNecoara

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
fixed in https://github.com/College-Kings/College-Kings/commit/bb3856c3685c27b4de16113465837e62f0d0141f
