### ISSUE TITLE
Username... where?

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

High

### Bug Description

Loaded an old CK1 save file, and well... See for yourself (the likes are working properly now):

![username](https://github.com/College-Kings/College-Kings/assets/108369429/6b5e1712-9d78-4bbf-8d0a-b2d76a4adbd2)

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
can you upload the save file so I can confirm when this is fixed

**Comment by nfaStefan** [comment]
[3-6-LT1.zip](https://github.com/College-Kings/College-Kings/files/11531163/3-6-LT1.zip)

**Comment by KiloOscarSix** [comment]
Fixed  in latest
