### ISSUE TITLE
Simplr messenger taking me to... the phone's one

### ISSUE THREAD

**Issue by nfaStefan** [College-Kings/College-Kings#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

High

### Bug Description

The title (and the evidence) kinda point it all:

https://www.youtube.com/watch?v=BLL3wLEbdsc&ab_channel=FlaviusNecoara

... Unless it's intended this way.

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
This is intended, saves having to keep simplr updated with it's own messenger
