### ISSUE TITLE
Game breaking translations

### ISSUE THREAD

**Issue by StefanGaming** [College-Kings/College-Kings#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Priority

High

### Bug Description

I have no idea about working with the submodules, so can't deal with it myself:

[New Text Document.txt](https://github.com/College-Kings/College-Kings/files/11961506/New.Text.Document.txt)

### Additional context

The markdown was so long, I had to put it in a Notepad file. Github said the comment was too long, over 60k characters or so... 💀 

### What is the OS version you are playing on?

Windows

**Comment by KiloOscarSix** [comment]
should be fixed in the latest push

**Comment by KiloOscarSix** [comment]
https://github.com/College-Kings/college-kings-translations/commit/64467166ea27db8bb5a0f6a38168ca200af1315c

**Comment by StefanGaming** [comment]
I pulled everything from the repo, updated the submodules and I still got it, so...

**Comment by StefanGaming** [comment]
> [College-Kings/college-kings-translations@6446716](https://github.com/College-Kings/college-kings-translations/commit/64467166ea27db8bb5a0f6a38168ca200af1315c)

... I had to update the submodule from VS Code, to make it work...

**Comment by KiloOscarSix** [comment]
haha, thats the best way to do it, have the modules on `main` or relevant branch and sync
