### ISSUE TITLE
V1 - Lauren's mouth should be opened\closed

### ISSUE THREAD

**Issue by dux90** [College-Kings/College-Kings#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Scene number

1584, 1589, 1594, 1599

### Priority

Normal

### Bug Description

lines 1584, 1594 - Lauren's mouth should be closed
lines 1589, 1599 - Lauren's mouth should be opened

### What is the OS version you are playing on?

Windows

**Comment by Irishgithub** [comment]
fixed in latest
